### ISSUE TITLE
Getting JSON parse exception when calling etSingleStockInfo

### ISSUE THREAD

**Issue by patrocinio** [luizjr92/stock-info#1]
I'm getting the following error / exception when calling a simple example:
```
> const si = require('stock-info');
undefined
> si.getSingleStockInfo('GOOG').then(stock => console.log);
Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events: { error: [Function: debugDomainError] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] } }
> (node:43039) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token r in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.res.on (/Users/edu/node_modules/stock-info/index.js:25:23)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
(node:43039) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:43039) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This is happening to any stock I try to query.

Thanks!

**Comment by patrocinio** [comment]
Never mind... 
Problem fixed when I moved to latest version.

Thanks for creating this library
